/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MwRadioButton {
        "checked"?: boolean;
        "disabled"?: boolean;
        "name": string;
        "value": string;
    }
}
declare global {
    interface HTMLMwRadioButtonElement extends Components.MwRadioButton, HTMLStencilElement {
    }
    var HTMLMwRadioButtonElement: {
        prototype: HTMLMwRadioButtonElement;
        new (): HTMLMwRadioButtonElement;
    };
    interface HTMLElementTagNameMap {
        "mw-radio-button": HTMLMwRadioButtonElement;
    }
}
declare namespace LocalJSX {
    interface MwRadioButton {
        "checked"?: boolean;
        "disabled"?: boolean;
        "name"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "mw-radio-button": MwRadioButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mw-radio-button": LocalJSX.MwRadioButton & JSXBase.HTMLAttributes<HTMLMwRadioButtonElement>;
        }
    }
}
